### ISSUE TITLE
cbr_now scheme

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#24] opened 2015-02-11 21:54 UTC
In older version of ED, cbr_now = cb/cb_max

ED2 Master has the following scheme: 
cbr_now = stress + (cbr_light - stress)*(cbr_moist - stress) / ((ddmort)*cbr_lightmax + (1-ddmort)*cbr_moistmax - stress)

Can someone explain the rationale for how this was developed?

It seems to me like a form more in line with what is described in the ED2IN and previous versions would be: 
cbr_now = cb/(ddmort*cbr_lightmax + (1-ddmort)*cbr_moistmax)

**Comment by mpaiao** [comment] 2015-02-12 00:30
I think the equation is 
cbr_now = stress + (cbr_light-stress)*(cbr_moist-stress) / (ddmort*cbr_light + (1-ddmort)*cbr_moist) - stress) (No cbr_lightmax or cbr_moistmax)

This is equivalent to say that 1/(cbr_now-stress) = ddmort / (cbr_light -stress) + (1-ddmort) / (cbr_moist - stress), where cbr_light = cbr / cbr_lightmax and cbr_moist = cbr / cbr_moistmax.  The reason I used this formulation back then was to make sure that the most limiting resource was driving mortality.

![screen shot 2015-02-11 at 22 17 44](https://cloud.githubusercontent.com/assets/5891904/6159392/f644c7e2-b23b-11e4-903b-0f40ebc6cf0b.png)

This method with light and soil moisture is not turned on by default, it would be applied only if IDDMORT_SCHEME is set to 1.

Since then I've simplified the calculation back to original, but defined cbr_max as if the cohort was at the top of the canopy and with fsw = 1.  This is still on my local branch only and I still need to clean the code, though.

**Comment by rgknox** [comment] 2015-02-24 21:15
This may be an aside, and sorry if this is tangential, but for what its worth: the default version of the code seems to be over-estimating carbon starvation mortality (and senescent mortality) in the tropics.  I know there is site to site variability, but the number is pretty darn high.

![mort_comp_v2](https://cloud.githubusercontent.com/assets/5891980/6359263/b23bc1f0-bc26-11e4-9e60-3897b4d1addc.png)

In the case above, radiation is the carbon starvation limiter, here is the mean par flux over the canopy depth compared to measurements.

![radtest_00-08_mercado_julyaugust](https://cloud.githubusercontent.com/assets/5891980/6359341/37ea2666-bc27-11e4-9828-328f430a9d7f.png)

Radiation

**Comment by crollinson** [comment] 2015-02-24 22:09
That seems to be in line with what several of us are seeing in temperate systems.  In my northeastern runs, we're having a hard time getting reasonable stem densities and @ryankelly-uiuc is having a hard time keeping trees alive as well and we think these are both tied to changes in the carbon balance implementation.  The current implementation of carbon balance does not quite line up with how DDMORT and CR are described in the ED2IN (at the very least DDMORT is backwards in the code), but I think the "severe_stress" term is also causing problems.

I've copied parts of an email thread from @ryankelly-uiuc, @mdietze, and myself below to bring that discussion back to here:

--------------------------------------------------------------------------------------------------
(Email from Ryan, comments in brackets my own; @mpaiao can you help clarify any of this?)
--------------------------------------------------------------------------------------------------
It [CBR] varies but they definitely go negative. I noticed before but was just thinking of “carbon balance”, which could sensibly be <0. 

[...] I think this is the intended behavior [based on the ED2IN; I had a similar interpretation]: 

cb_Xmax = maximum carbon balance if X was not limiting (X = light or moisture)
cbr_severe_stress = some minimum CBR that a plant can have, presumably positive. Used to be 0 in older ED2 versions. 

cbr_X = max( cb_actual / cb_Xmax, cbr_severe_stress)

ddmort_const = a namelist parm = proportional contribution of cbr_light to overall cbr

cbr_now = this month’s cbr = ddmort_const*cbr_light + (1-ddmort_const)*cbr_moist

cbr_bar = running mean of last 12 months’ cbr_now (for trees anyway; fro grasses cbr_bar = cbr_now)

mortrate2 = mortality due to low CB = mort1 / (1+exp(mort2*cbr_bar)), where mort1 & mort2 are PFT parms

[...] First of all, cbr_severe_stress is defined to be <0 (~ -0.8 for deciduous trees by default). Second, cbr is forced equal to cbr_severe_stress when cb_Xmax < 0. However if cb_Xmax>0 but cb<0, the ratio is calculated normally and the result is a negative CBR. [...]

Most of this was not an issue in earlier versions of ED (going back as far as CD’s thesis version, r82 I think), because the separate light vs. moisture terms were not included, nor was cbr_severe_stress. However even in the older code it looks like it was possible for CBR to be negative if cb_actual<0 and cb_max>0. This made me think maybe I’m just missing something, and carbon balance “ratio” is just a lousy term for an index that can go negative. This alone isn't *that* big a deal—per the last equation above it changes the theoretical maximum mortality due to CB from 0.5 to 1.0. But the other (newer) problems make negative CBR (—> mortality >0.5) actually quite likely, as far as I can tell.

--------------------------------------------------------------------------------------------------
CR: I have tweaked things a bit in my branch of ED, but have held off making a pull request until I've had a chance to separate CBR, Canopy CO2, and PFT parameterization problems. After looking at my latest runs, I don't think the version I have in my branch is currently solving the density-dependent/CBR mortality issue, so I wouldn't recommend anybody pulling it.

**Comment by mpaiao** [comment] 2015-02-25 01:22
I described this is in my dissertation, section F.3 (http://dash.harvard.edu/handle/1/11744438).   The equation in ED2IN is old indeed, it should be:
1/(cbr_now-cb_stress) = ddmort / (cbr_light-cb_stress) + (1-ddmort)/(cbr_moist-cb_stress)

Also, my mistake in the previous comment,  I should have said DDMORT_CONST = 1 (not IDDMORT_SCHEME=1) turns off moisture limitation and reduces the carbon limitation to the original cb definition (light only).   Line 324 of structural_growth becomes:
cbr_now = cbr_stress + (cbr_light - cbr_stress) * (cbr_moist - cbr_stress) / (cbr_moist - cbr_stress)
cbr_now = cbr_stress + cbr_light - cbr_stress = cbr_light

I can think of two possibilities for higher mortality rates using newer versions. 
1. I reverted the cbr_bar calculation to the original ED-1.0 (running average of CBR, instead of average of actual CB divided by average of maximum CB), it may be worth trying the original formulation to see if reduces the mortality.  That said, mortality rates have been always high when I compared to the observations in the tropics, even before I applied the changes, not sure about mid-latitude sites, it may be worth testing.
2. Before cbr_bar would be set to zero if cb_max ≤ 0.  In this case mort_rate(2) becomes 0.5*mort1, thus lower than when cb_act <0 and cb_max > 0. I may have missed something but this didn't make sense to me: f the cohort cannot assimilate enough carbon even under ideal conditions, this cohort is just not viable.  The current code  sets cbr_light=cbr_severe_stress when cb_lightmax < 0, so mort_rate(2) ~ 1.0*mort1.  If this is the case, then I don't think the problem is that the model is setting set mort_rate(2) = 1.0*mort1, but why is cb_lightmax so low in the first place.

**Comment by ryankelly-uiuc** [comment] 2015-02-26 14:49
Thanks Christy for getting this onto github, and Marcos for clarifying a lot of the reasoning. 

It looks like much of our confusion simply came from some out of date code comments in the ED2IN and structural_growth.f90, which suggested that cbr_now is a simple weighted average of cbr_light and cbr_moist. I understand now that you decided to use a harmonic mean instead, and used cbr_severe_stress as a practical representation of the theoretical -Inf lower bound. Please let me know if I’m still missing something, but I think that makes sense. 

In any case, it sounds like lots of us have anecdotal evidence that ED is at least in some cases overestimating CB-based mortality. This is something I’m hoping to address in the context of my current project with Mike et al., which aims to use data from FIA and a bunch of long-term census plots to constrain demographic processes in ED. Advice and experiences along those lines are welcome (though perhaps beyond the scope of this thread).

**Comment by crollinson** [comment] 2015-03-04 03:09
Okay, so I've made a set of changes that seem to have solved most of my problems.  I haven't done a thorough quantification and graphing of all the moving parts, but the apparent "carrying capacity" of my system is up to something reasonable now.  All of my changes can be seen in my "debug" branch found at: https://github.com/crollinson/ED2/tree/debug (sorry in advance for the messy commits..)  

What I've done is as follows:

1) implemented the cold deciduous fixes found here: https://github.com/EDmodel/ED2/issues/25 

2) Create temporary cb_act, cb_lightmax, & cb_moistmax values that are calculated as the sum of the previous 12 months.  This follows what was done in an older version of ED. (lines 297-317 of structural growth in my code) cpatch%cbr is now cbr_now and no longer the running average

3) changed the cbr_now code to now be:
                 cbr_now =  ddmort_const  * max(cbr_light, cbr_severe_stress(ipft)) &
                 			 + (1.0 - ddmort_const) * max(cbr_moist, cbr_severe_stress(ipft)) 
I think this is functionally similar to what Marcos had, but is a bit more straight-forward and more similar to the ED2IN documentation.  I have cbr_severe_stress = -0.4, which with dmort2=20 results in 98% mortality.  Setting the cbr_severe_stress constraint is probably no longer necessary, but was included to help a tree be able to get out of severe stress with cbr calculated as a running mean.

I also made a change in my PFT parameterization where I brought the water_conductance I was working with (from inherited PFT parameterizations) back down to closer to the ED default.  If water conductance is too high, the trees end up being extremely water limited and cbr_lightmax is almost always negative.  (This may have been an artifact of the previous version not having the explicit water density-dependent stress.)

Hope this helps folks!

**Comment by mpaiao** [comment] 2015-03-04 19:26
Just one comment about your 3.  The reason I switched to 1/(cbr-cbr_stress) instead of the way that is written in ED2IN is to make sure that if the cohort is under severe stress due to one environmental condition, then the cohort is under stress.  If you use the "linear" weighting, then a combination of high moisture stress and no light stress would make the tree not stressed.   I'm sending the parameter space map for the two cases assuming ddmort = 0.5; inverse is the one in the code, and linear is the one in ED2IN.  Note that in the linear case you could have very low mortality rates even with negative cbr_light. 

![cnet_ddmort_wl_interest](https://cloud.githubusercontent.com/assets/5891904/6491135/f498897a-c289-11e4-81e3-e213a647a140.png)
![clin_ddmort_wl_interest](https://cloud.githubusercontent.com/assets/5891904/6491128/e7b960f8-c289-11e4-85d1-e11fea7d808e.png)

**Comment by mdietze** [comment] 2015-03-04 19:43
@mpaiao thank's for the clarification, I agree that the inverse weighting seems to make more sense. Another alternative along that same logic would just be to just min/max to select the most stressed state and not impose any interaction. Ultimately what we should probably be done is to let the data decide which is correct.

Another important point that came up in our lab group meeting last friday, when @ryankelly-uiuc presented some of his work on sorting out mortality, is that the running mean cbr should be the mean of the last 12 months actual CB over the mean of the last 12 months CB maximum (given whatever weighting scheme you want to use). Essentially, we should be using a ratio of means, not a mean of the ratio. Simple and very real case: imagine a temperate tree that has large uptake mid summer (large positive CBR) and then in the winter runs a tiny negative CB because there's no GPP but there's a small amount of Ra, yet runs a large negative CBR because all the fluxes are small in the winter. The plant's actual total carbon balance is massively positive, but the mean of the CBR's will be around zero or even negative, and thus ED kills the tree.

**Comment by mpaiao** [comment] 2015-03-04 20:02
@mdietze Good point on the means.  The mean of the ratio is the ED-1.0 style, and I was probably thinking on tropical trees when I was using it, but I agree this won't work on temperate sites so we should use the ratio of the 12-month means.

Another option on cbr is to revert back to a single cb / cb_max, and define cb_max as the cb if the cohort was at the top of the canopy AND fsw was 1.

**Comment by crollinson** [comment] 2015-03-04 22:23
thanks @mpaiao and @mdietze 

It looks like having an option to use a single cb_max would be a good thing and wouldn't take too much tweaking of the code to put that in, possibly tweaking the DDMORT_CONST constraints so that DDMORT_CONST == -1 triggers single cb_max (full light, full water).  Based on Mike's comments about letting the data drive this in the future, I think we want to add this as an option rather than undoing what's already there.

Thoughts? @ryankelly-uiuc?  

If this sounds good to y'all, then I can go ahead and do that and then submit a pull request that has the single-stress option, the running CB (not CBR), and Marcos' inverse cbr scheme.  Or if someone else thinks it would require even less tweaking & cleaning of their code to implement, that'd be even better.  I was throw the suggested phenology changes from Issue #25, but based on Ryan's recent comments, I think we should separate that issue from these fixes.

**Comment by mpaiao** [comment] 2015-03-05 00:11
I like the idea to keep all options for the time being.  I was doing some tests with a single cbr last year, though not as an option.  The changes were simple, and the code is up on my local ED2 branch if you would like to have a look, or I can implement the options once I'm back to ED work (it may be a week or two until it happens).

**Comment by ryankelly-uiuc** [comment] 2015-03-05 02:12
I agree with @mpaiao and @crollinson —leaving all options open makes sense at this point, at least until we have compelling reasons to favor one scheme over another. I also like @mdietze 's idea to let the cbr calculation be based strictly on the most limiting resource, Liebig style. This would also be easy to implement. 

One minor thing I would suggest is to control the scheme used through the IDDMORT_SCHEME flag, rather than special values of the DDMORT_CONST. Just seems a little safer to me. 

@crollinson , I'm sure your version of the code is closer to the goal than mine at this point, but I'm happy to help any way I can.

**Comment by dlebauer** [comment] 2015-03-09 18:50
@Viskari could you comment on the changes you made to fix this issue independently? Have they been merged into the master? Or are they on a branch?

Has anyone written a test for this issue?

**Comment by crollinson** [comment] 2015-03-11 01:13
For anyone interested, I now have a working branch (gh24) in my repository where we have implemented CBR_SCHEME where you have to specify how you want to calculate CBR in the ED2IN.  This builds on commits from @ryankelly-uiuc a few days ago.  

I haven't issued a pull request yet since I haven't fully tested it with my stuff, but it's there if others want to pull it and check it out.  Hopefully we'll have a pull request to get this into the ED2 mainline by the end of the week.

**Closed** 2015-04-17 23:32 UTC
