### ISSUE TITLE
Bug in plant hydro scheme number 1

### ISSUE THREAD

**Issue by nguyenlong923** [EDmodel/ED2#245] opened 2018-04-11 09:07 UTC
Hello everyone, 

I am a new ED2 user and I am experiencing a crash when running the up-to-date ED2 version with the plant hydro scheme number 1.
I want to make a 300 year simulation (1700 - 2000) in Paracou, start from near-bare ground (IED_INIT_MODE   = 0), with the PFT 2, 3, 4, and the PLANT_HYDRO_SCHEME = 1. The simulation crash at 1st January 1771 due to the following issue:
    ---> File:        rk4_integ_utils.f90
    ---> Subroutine:  print_rk4patch
    ---> Reason:      IFLAG1 problem. The model didn't converge!
I found that the PFT 2  has wood temperature off-track (3.5100E+02) and wood water zero (0.0000E+00). The problem could not be solved by re-running ED2. However, the model work well if PFT 17 (lianas) is added.

Are there anyone experience the similar problem or know the reason?

Kind Regards,

Long.

P.S:  I attached the record of terminal with the bug in case someone want to take a closer look.
[ED2 bug.txt](https://github.com/EDmodel/ED2/files/1898078/ED2.bug.txt)

**Comment by mdietze** [comment] 2018-04-11 10:08
@nguyenlong923, what leads you to hypothesize that the plant hydro scheme is the issue. Does the model run successfully when plant hydro is set to other values? Why would adding lianas alleviate the presumed bug in the hydro scheme? Why would plant hydraulics cause an error in wood temperature? I'm not saying you're wrong, and I definitely appreciate how frustrating ED2 crashes are, I'm just not sure why you think the problem is isolated to a bug in the hydraulics vs somewhere else in the code.

Also, when you say that rerunning the code made no difference, did you rerun with the exact same settings (which I agree would make no difference) or did the run crash even after reducing the integrator timestep?

Finally, you might try a run that starts from different initial conditions (e.g. modern observations). My experience is that ED2's energy balance is particularly sensitive to bare ground starts because the plant thermal mass is so small relative to the magnitude of the fluxes in and out.

**Comment by xiangtaoxu** [comment] 2018-04-11 12:39
The current plat hydro version does have some bugs in budget calculation especially for small cohorts. I have some bug fixing updates in my personal version. I will create a PR this week to push the updates.

In addition, are you setting non zero trait plasticity scheme in ED2IN? That is still under test for Amazon rainforest and can lead to erroneous results

Xiangtao

**Comment by xiangtaoxu** [comment] 2018-04-11 12:41
I agree with @mdietze that it would be helpful to run the same simulation with no hydraulics

**Comment by nguyenlong923** [comment] 2018-04-11 13:11
@mdietze , I hypothesize that the plant hydro scheme is the issue because I wast testing the hydraulic scheme and PFT 17 (lianas) in my project with 4 setups:
PLANT_HYDRO_SCHEME = 0 or 1 (with or without hydraulics)
PFT = 2, 3, 4 or 2, 3, 4, 17 (with or without lianas)
Other parameters were unchanged 
Only the set with PLANT_HYDRO_SCHEME = 1 and PFT =  2, 3, 4 causing the problem. And when i re-run, I used the same setting.
I am not sure why adding lianas can improve the situation. But you are right, I might jump to conclusions too soon. Thanks for you suggestion, I will try to look at the initial conditions as well.

**Comment by nguyenlong923** [comment] 2018-04-11 13:16
@xiangtaoxu : No, I set trait plasticity scheme to zero. Also, I did not use other schemes in your new updates such as stomata scheme. They were all kept at ED2 default except for the hydro scheme (change between 0 and 1).

I am looking forward to your next update.

Long.

**Comment by xiangtaoxu** [comment] 2018-04-11 19:39
@nguyenlong923 
Try this version https://github.com/xiangtaoxu/ED2-1/tree/hydro and see whether the errors still pop up. This version has successfully run for hundreds of years in several tropical sites.

I have also created a PR for the update

**Comment by xiangtaoxu** [comment] 2018-04-15 18:42
@nguyenlong923 What value did you use for IBRANCH_THERMO? I think there might be a bug in wood temperature calculations when IBRANCH_THERMO = 0

**Comment by nguyenlong923** [comment] 2018-04-15 19:08
@xiangtaoxu I set IBRANCH_THERMO = 1.
Anyway, I have just finished my simulation this afternoon with the version that you are trying to push. The problem seems to be solved.
I think we can close the case now.

Thanks so much!

Long.

**Comment by xiangtaoxu** [comment] 2018-04-16 02:37
@nguyenlong923 Great to know that it is solved! I think there might still be a problem for IBRANCH_THERMO = 0. I will close this issue and probably create another PR after I explore more

**Closed by xiangtaoxu** 2018-04-16 02:37 UTC
