### ISSUE TITLE
SFCWATER_DEPTH and H5Dwrite error at end of the year

### ISSUE THREAD

**Issue by fabeit** [EDmodel/ED2#114] opened 2015-08-20 14:59 UTC
I get this error right when the model transitions from Dec 31 to Jan 1, starting the model on Jan 1 works just fine.

```
---> Making new patch, with area=  1.24222E-02  for dist_type=     3
Total count in node        1 for grid        1 : POLYGONS=        1 SITES=        1 PATCHES=        2 COHORTS=       10
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139882996623168:
  #000: ../../../src/H5Dio.c line 234 in H5Dwrite(): can't prepare for writing data
    major: Dataset
    minor: Write failed
  #001: ../../../src/H5Dio.c line 351 in H5D__pre_write(): file selection+offset not within extent
    major: Dataspace
    minor: Out of range
 Variable name:    SFCWATER_DEPTH                                                  
 Global dimension:                     1                    2                 8784                    0                    0                    0
 Chunk dimension:                      1                    2                    1                    0                    0                    0
 Chunk offset:                         0                    0                  743                    0                    0                    0
 Count:                                1                    1                    1                    0                    0                    0
 Stride:                               1                    1                    1                    0                    0                    0
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

--------------------------------------------------------------
                     !!! FATAL ERROR !!!                      
--------------------------------------------------------------
    ---> File:        h5_output.F90
    ---> Subroutine:  h5_output
    ---> Reason:      Could not write hyperslab into the dataset
--------------------------------------------------------------
 ED execution halts (see previous error message)...
--------------------------------------------------------------
```

**Comment by DanielNScott** [comment] 2015-08-20 16:43
Which output file is it trying to write the variable to? It looks like (based on the dimensions) It's trying to write an hourly variable on a leap year into a yearly spot reserved for a yearly mean. I'd say check the write-keys in ed_state_vars().

**Comment by mpaiao** [comment] 2015-08-20 16:53
Someone e-mailed me a similar question a few days ago, and apparently turning on IQOUTPUT=3 fixed this problem.  @fabeuw in case your IQOUTPUT is set to 0, could you please check if it runs with IQOUTPUT=3?  If this is the case, I will check why this is happening.

**Comment by DanielNScott** [comment] 2015-08-20 17:16
@mpaiao wait, can you tell that from the output somehow? Are you just telepathic?

**Comment by mpaiao** [comment] 2015-08-20 17:21
@DanielNScott No, I can't tell from the output... it's just that someone else asked me the same question recently (by e-mail, not in github), and for their case turning on IQOUTPUT made the trick.

**Comment by fabeuw** [comment] 2015-08-20 17:24
@DanielNScott @mpaiao in my case it's NL%ITOUTPUT that makes the run crash, I turned all outer outputs on and it works fine, as soon as NL%ITOUTPUT is on I get the crash. It also crashes if NL%ITOUTPUT is the only one on. With all outputs off it also works.

**Comment by DanielNScott** [comment] 2015-08-20 17:26
Yeah, that makes perfect sense. It sounds like the issue is exactly what I pointed to. There's an output key error in ed_state_vars.

**Comment by DanielNScott** [comment] 2015-08-20 17:28
Looks like this is it:

```fortran
      if (associated(csite%sfcwater_depth)) then
         nvar=nvar+1
           call vtable_edio_r(npts,csite%sfcwater_depth,nvar,igr,init,csite%paglob_id, &
           var_len,var_len_global,max_ptrs,'SFCWATER_DEPTH :33:hist:opti') 
         call metadata_edio(nvar,igr,'No metadata available','[NA]','m') 
      end if
```

Shouldn't say opti.

**Comment by fabeuw** [comment] 2015-08-20 17:29
I believe I have the latest code from the master branch. I don't really need that output at the moment. @mpaiao which outputs do you usually turn on? Is there a specific use for the instantaneous fluxes?

**Comment by DanielNScott** [comment] 2015-08-20 17:33
@mpaiao yeah, sorry, I misread what you'd written. I'd read "in case your IQOUTPUT is set to 0" as "in your case IQOUTPUT is set to 0" then realized it which is why I deleted the comment.

**Comment by fabeuw** [comment] 2015-08-20 17:41
I am not sure if I will be able to correct this alone, it seems we have issues with two of these outputs. @mpaiao does that other person have the latest build?

**Comment by DanielNScott** [comment] 2015-08-20 17:44
You should just be able to replace:
```fortran
           call vtable_edio_r(npts,csite%sfcwater_depth,nvar,igr,init,csite%paglob_id, &
           var_len,var_len_global,max_ptrs,'SFCWATER_DEPTH :33:hist:opti') 
```
with 
```fortran
           call vtable_edio_r(npts,csite%sfcwater_depth,nvar,igr,init,csite%paglob_id, &
           var_len,var_len_global,max_ptrs,'SFCWATER_DEPTH :33:hist') 
```
and do the same for the other variable. Then recompile and see if you hit the same error, which I'm fairly certain you won't.

**Comment by mpaiao** [comment] 2015-08-20 18:03
@fabeuw @DanielNScott sorry, I'll take back what I said, I'm not sure if it fixed the problem, he said he was using a previous version and he was going to test the new version, but I'm not sure it fixed.  I'll check with him.

@fabeuw for long-term runs, I normally save the -S- files and -Q- files.  I don't think I've ever used ITOUTPUT... When I have a chance I will try to reproduce this error using some debugger software.

**Comment by femeunier** [comment] 2018-11-08 17:28
Just to close this issue:

I had exactly the same problem as @fabeit when trying to produce the flux tower file ('T') and it was fixed with the trick of @DanielNScott, changing the command in memory/ed_state_vars.f90 from:
`call vtable_edio_r(npts,csite%sfcwater_depth,nvar,igr,init,csite%paglob_id, &
           var_len,var_len_global,max_ptrs,'SFCWATER_DEPTH :33:hist:opti')`
to

`call vtable_edio_r(npts,csite%sfcwater_depth,nvar,igr,init,csite%paglob_id, &
           var_len,var_len_global,max_ptrs,'SFCWATER_DEPTH :33:hist')` 

solved this issue that can be closed, I guess.

**Comment by mdietze** [comment] 2018-11-08 21:49
Note that this “solves” the problem by eliminating the ability to output snow depth. Which may be fine for all you tropical folk, but is a bit inconvenient in temperate, boreal, and tundra systems. Probably an OK short term fix, but it would be nice to restore, and to understand why this worked for a decade before it broke

**Comment by mpaiao** [comment] 2022-08-11 19:05
Closing issue as pull request #354 addresses this.

**Closed by mpaiao** 2022-08-11 19:05 UTC
