### ISSUE TITLE
Cold Deciduous PFT Growth

### ISSUE THREAD

**Issue by DanielNScott** [EDmodel/ED2#25] opened 2015-02-11 23:12 UTC
I've found some sort of issue with cold deciduous pft growth at Harvard Forest, which may apply to other sites, and which looks like a code problem to me. These PFTs don't grow, at least under my inherited prescribed phenology scheme, so others running with cold-deciduous PFTs probably want to look at a breakdown of basal area by PFT to determine if this is the case for them as well. See the panels below, particularly the basal area plots. 

- Each set of panels is for a pft class
   - the first 9 are for conifers
   - the second 9 are for hardwoods.
- Each plot has two trajectories;
   - One in which I've changed the allowed hardwood growing season from strictly June to May - Aug.
      - This is not presently a proposed fix, just an experiment.
   - One in which I haven't, meaning hardwoods can only add to BDEAD in June (for lat>0)

Conifers:
![pools - co](https://cloud.githubusercontent.com/assets/7492269/6158466/7084a56e-b1ff-11e4-9e93-040316b5946f.jpg)

Hardwoods (Cold Deciduous):
![pools - hw](https://cloud.githubusercontent.com/assets/7492269/6158467/70858506-b1ff-11e4-8c84-42c7bba14e7b.jpg)

I believe the issue has to do with the phenology flag system. Hardwoods can add to bdead provided the following code snippet is cleared (in structural_growth.f90:plant_structural_allocation):

```fortran
   !----- Check whether this is late spring... --------------------------------------------!
   late_spring = (lat >= 0.0 .and. current_time%month ==  6) .or.                          &
                 (lat <  0.0 .and. current_time%month == 12) 
   !---------------------------------------------------------------------------------------!


   select case (ibigleaf)
   case (0)
      !------------------------------------------------------------------------------------!
      !      Size and age structure.  Calculate fraction of bstorage going to bdead and    !
      ! reproduction.  First we must make sure that the plant should do something here.  A !
      ! plant should not allocate anything to reproduction or growth if it is not the      !
      ! right time of year (for cold deciduous plants), or if the plants are actively      !
      ! dropping leaves or off allometry.                                                  !
      !------------------------------------------------------------------------------------!
      if ((phenology(ipft) /= 2   .or.  late_spring) .and. phen_status == 0)    then
```

Here's a plot of phen_status by month, as seen by plant_structural_allocation, for 94,95, and 96.

![hf_phenology_stat_by_pft](https://cloud.githubusercontent.com/assets/7492269/6174846/7fa65ea0-b2a6-11e4-990c-3fae8d68db91.jpg)

You can see that phen_status is typically not 0 for hardwoods in June. This is despite elongf being 1.0 as of late May in all the HDF5 output I've seen, which would seem to indicate that the prescribed phenology itself is not the issue. I'll update this when I know why...

Any ideas/commentary appreciated...

**Comment by DanielNScott** [comment] 2015-02-13 22:27
Ok, I'm fairly certain the issue is this code from growth_balive.f90, the allocate_plant_c_balance subroutine.

```fortran
   !------------------------------------------------------------------------------!
   !     Check whether we are on allometry or not.                                !
   !------------------------------------------------------------------------------!
   on_allometry = 2.0 * abs(balive_aim - cpatch%balive(ico))                      &
                / (balive_aim + cpatch%balive(ico))          < 1.e-6
   if (cpatch%elongf(ico) == 1.0 .and. on_allometry) then
      !---------------------------------------------------------------------------!
      !     We're back to allometry, change phenology_status.                     !
      !---------------------------------------------------------------------------!
      cpatch%phenology_status(ico) = 0
   end if
   !------------------------------------------------------------------------------!
else
   !------------------------------------------------------------------------------!
   !     Put carbon gain into storage.  If we're not actively dropping leaves or  !
   ! off-allometry, this will be used for structural growth at the end of the     !
   ! month.                                                                       !
   !------------------------------------------------------------------------------!
   cpatch%bstorage(ico) = cpatch%bstorage(ico) + carbon_balance
   nitrogen_uptake      = nitrogen_uptake      + carbon_balance / c2n_storage
```

This appears problematic because in some debugging output I've created it's clear that the if virtually never gets entered into, despite available carbon being high enough that plants "should" transfer all that is necessary to be put back on allometry, and at least to 3 or 4 digit accuracy they do. Changing the on_allometry calculation to 

```fortran
   on_allometry = abs(balive_aim - cpatch%balive(ico))/balive_aim < 0.01
```

 fixes the problem, which seems to indicate that there is just a loss in accuracy somewhere across the many calculations used to create the 'aim' values. I'll see if I can upload an attachment with supporting info for those interested, transfer the 'fix' and debugging code snippets to a mainline branch, see if the accuracy can be 0.001 instead (but can you really say a plant is off alometry if it's leaf/root tissue deviate from the aim by < 1%?) do the EDTS and all that...

Also, note that this change doesn't affect the leaf/root trajectories independently of the now-growing basal-area, because transfers to roots and leaves in accordance with their aimed-for values happen regardless of whether phenology_status is 0 or 1.

**Comment by mdietze** [comment] 2015-02-14 00:27
Sounds like a good fix to me. In the short run I'm perfectly happy with that threshold being 0.01 or 0.001 and much prefer that to ad hoc changes to the growing season. Ultimately, it probably does make sense to have a way to spread out cold deciduous growth, but the reality of what's going on in trees is non-trivial and we wouldn't want to introduce more uncertainties than we end up reducing.

**Comment by ryankelly-uiuc** [comment] 2015-03-04 22:18
Based on my own tinkering the last few days, this bug is at least sometimes caused by plants already having more C in a particular pool (leaf, root, etc.) than the target value calls for. The code doesn't allow C loss from such pools, so actual biomass in the pools then deviates from target values, and the on_allometry check fails as Daniel describes above. 

A few thoughts on what to do about this:

1) Maybe actual biomass should never exceed the maximum value for a given pool. I don't know why this happens but we could track the cause down and stop it.

2) We could allow plants to transfer C among pools to get back on allometry. I tried this and it works fine. When there is enough C to go around, all pools fill up to computed max value, even if it requires taking from a pool that has more than enough. When C is limited, I distribute available C among pools so that they are all the same proportion of their max values. This approach may be unrealistic if it ever causes large quantities of C to move from one pool to another.

3) We could just change the test for on_allometry to pass whenever all pools end up at *or above* their target values. Pools that are oversized will get no new C, as in the current code, so cohorts still should tend towards the right allometry over time even if they're somehow above max pool sizes. In the meantime, as long as all pools have at least as much C as they should, phenology status will be set to 0.

**Comment by mdietze** [comment] 2015-03-05 12:16
@ryankelly-uiuc definitely don't do option 2. ED used to do this (it just had two pools, balive and bdead, and the partitioning to leaf, sapwood, root, etc was implicit) and it was actually a decent chunk of work to remove this so that we could get resprouting working. That is to say, there are actually times when being OVER the allometry is the correct answer. Furthermore, only the storage pool is non-structural  -- plants can't undo the cellulose and lignin they've put down in cell walls. Allowing them to do so may solve a short term problem but in the long term it's going to create more problems.

Option 3 seems like the most obvious solution (I know I had a version like this at one point).

WRT Option 1 -- I agree we ultimately do need to track down what's causing trees to go over their allometries in cases where we're not expecting them to do so.

**Comment by ryankelly-uiuc** [comment] 2015-03-05 13:31
@mdietze Thanks for the feedback. RE: Option 2, agreed that cellulose shouldn't be swapped around pools willynilly. I just thought if there's really no reason that pools ever get oversized, then when they do it may really be a machine precision thing, in which case fudging the pools wouldn't be a big deal. 

Anyway I agree option 3 sounds best, especially after your explanation that plants should be allowed to be over allometry. How does this sound to you, @DanielNScott (or others)? If everyone's OK with it I'll implement as discussed, i.e. on_allometry=T iff all C pools are >= target values.

**Comment by DanielNScott** [comment] 2015-03-05 18:10
I think that sounds like a good idea. Maybe you and I @ryankelly-uiuc should coordinate on the branch? I added a simple file-output debugging option which I think I mentioned above for the alloc_plant_c_bal S.R. which I think it would be pragmatic to keep. I have a clean branch with the appropriate changes (except the >= part) that I just hadn't pushed to the mainline yet. I'll push it to my repository in a minute and if we want to keep it we can just change the conditional. Let me know what you think.

**Comment by ryankelly-uiuc** [comment] 2015-03-05 18:13
@DanielNScott , that sounds good to me. I'll take a look when you push it and see if I have anything to add. Debugging option will be nice to have.

**Comment by DanielNScott** [comment] 2015-03-06 02:12
Should have said "today" instead of "in a minute." It's a classic Californianism, sorry.
@ryankelly-uiuc I just pushed the change to my master branch. I think at the code meeting we decided this wasn't something that needed test-suite vetting so I'm submitting a pull-request too, which I guess is where folks should comment now.

**Comment by dlebauer** [comment] 2015-03-09 18:23
@Viskari could you comment on the changes you made to fix this issue independently? Have they been merged into the master? Or are they on a branch?

**Comment by ryankelly-uiuc** [comment] 2015-03-09 18:29
@dlebauer ,@Viskari—the issue we were just discussing is gh-24, not this one.

**Closed** 2015-03-09 19:27 UTC

**Comment by ryankelly-uiuc** [comment] 2015-03-09 19:29
Looks good, @DanielNScott . Thanks again. (Sorry I missed your reply the other day. I guess I replied "in a minute"?)
