### ISSUE TITLE
How to add a new grid level variable

### ISSUE THREAD

**Issue by sy-li** [EDmodel/ED2#269] opened 2019-03-19 05:16 UTC
I try to add a new variable in cgrid to read and store disturbance rate data from external sources, but run into an error: “malloc(): memory corruption (fast): 0x000000004dd11540”.
I noticed in ed_state_vars.f90, cgrid/cpoly doesn't have subroutines for deallocation - why csite/cpatch does but cgrid/cpoly doesn't? Would it be possibly the reason of error?

**Comment by mdietze** [comment] 2019-03-19 13:26
I don't think the deallocation is the issue. These variables don't deallocate because they're not dynamics -- the number of grid cells and polygons in fixed within a given run.

Also, there's already code for reading and storing external land use and disturbance rate data (as well as a second option for prescribing individual 'events'). Is there a reason that you can't use that existing code by just reformatting your disturbance data into that format? You might also check in with @crollinson who is working on extending the disturbance and management schemes.

**Comment by xiangtaoxu** [comment] 2019-03-19 14:37
@sy-li I agree with Mike. The number of grid/polygons is fixed after the program processes the ED2IN. The whole structure will be deallocated automatically at the end of the run.

Could you paste the code you have added so that we can give more advice?

**Comment by mpaiao** [comment] 2019-03-19 15:05
@sy-li this looks like some bug in the size of allocation, but as @xiangtaoxu mentioned, please point us to your code, so we can take a look.

@mdietze and others, I updated the disturbance matrix a few years ago to distinguish multiple disturbance types (1 = pasture, 2 = forest plantation, 3 = tree fall, 4 = fire, 5 = abandonment, 6 = log felling, 7 = skid trails/roads, 8 = croplands).  Types 1-6 are already in the mainline.  @xiangtaoxu and I are working on merging the my branch with the mainline, and this merge will have a few additional changes.  I shared my branch with @crollinson at some point last year, so I believe hers is similar to mine.  In any case, it may be a good idea to coordinate these changes in disturbance rates, to make sure we won't create too many code merge conflicts.

**Comment by sy-li** [comment] 2019-03-19 16:21
@mdietze @xiangtaoxu @mpaiao Thank you for taking a look at my problem. I can understand the reason why deallocation is not necessary now. The changes I made in ed_state_vars.f90 are:
In type ed_type, add:
`real, pointer, dimension(:) :: tdr_py`
In subroutine allocate_edtype(cgrid,npolygons), add:
`allocate(cgrid%tdr_py(npolygons))`
In subroutine nullify_edtype(cgrid), add:
`nullify(cgrid%tdr_py)`
In subroutine filltab_edtype_p11inst(cgrid,igr,init,var_len,var_len_global,max_ptrs,nvar), add:
`      if (associated(cgrid%tdr_py)) then
         nvar=nvar+1
         call vtable_edio_r(npts,cgrid%tdr_py,nvar,igr,init,cgrid%pyglob_id, &
              var_len,var_len_global,max_ptrs,'TREE_DIST_RATE_PY :11:hist:anal:year')
         call metadata_edio(nvar,igr,'Treefall disturbance rate by polygon','[1/yr]','ipoly')
      end if
`
The code was able to be complied after I made changes, but had error when I executed it.
@mdietze Thank you for pointing out this option. I'm not familiar with using this function to customize land use and disturbance rate data yet, but will try it out. The dataset I have is simply a text file of disturbance rate for each grid cell, so originally I thought a direct approach could be just replacing the value for NL%TREEFALL_DISTURBANCE_RATE.

**Comment by xiangtaoxu** [comment] 2019-03-19 17:54
@sy-li Can you also post the full error message, including the context as well as your ED2IN?

**Comment by sy-li** [comment] 2019-03-19 18:12
@xiangtaoxu Here they are. Thank you.
[error message.txt](https://github.com/EDmodel/ED2/files/2984862/error.message.txt)
[ED2IN-SA-B(new).txt](https://github.com/EDmodel/ED2/files/2984864/ED2IN-SA-B.new.txt)

**Comment by sy-li** [comment] 2019-03-19 19:10
And here's the error message I got if compiling the code using debugging mode. Any clue or advice would be appreciated.
[error message-dbg.txt](https://github.com/EDmodel/ED2/files/2985188/error.message-dbg.txt)

**Comment by xiangtaoxu** [comment] 2019-03-25 01:14
I did some test and the problem is likely because @sy-li did not initialize the new grid-level variable in ed_type_init.f90. I do not fully understand how that leads to segmentation fault when using other grid-level variables. Do uninitialized variables contaminate the memory allocation of a Fortran structure in the debugging compilation?

Anyway, on my end, the model runs fine if the tdr_py is properly initialized in ed_type_init.f90

**Comment by mpaiao** [comment] 2019-03-25 15:08
@xiangtaoxu This is exactly what uninitialized variables do, especially if you compile the code with -O3.  The code crashes become unpredictable, and often at places that have little to do with the actual bug.  My recommendation is always the same: to compile and run the code with very strict debugging options.  The code will then crash exactly at the first code exception, which saves time.

For reference, these are the compilation flags I normally set for debugging ED.

Intel:
```
F_OPTS= -FR -O0 -recursive  -check all,noarg_temp_created -g -debug extended         \
        -debug-parameters all -fpe0 -no-ftz -traceback -ftrapuv -fp-stack-check      \
        -implicitnone -assume byterecl -warn unused -warn uncalled -warn usage       \
        -warn declarations -gen-interfaces -qopenmp -diag-error=all -static
```

Gfortran:
```
F_OPTS= -O0 -ffree-line-length-none -g -fimplicit-none -Wall -finit-real=snan        \
        -finit-integer=-2147483648 -ffpe-trap=invalid,zero,overflow,underflow        \
        -fcheck=all -frecursive -fsignaling-nans -Werror -fopenmp -static
```

other options may exist and be helpful, especially in gfortran, which I don't normally use.

**Comment by sy-li** [comment] 2019-04-18 18:37
Thank you all, and special thanks to @xiangtaoxu. This issue was resolved by properly initializing the added variable in ed_type_init.f90, then the model can run normally in opt mode.
For the error message I've uploaded generated in debugging mode - it seems to be a platform-specific problem, and is likely due to incompatible compiler. I am still working with HPC staff in ND.

**Closed** 2019-04-18 18:38 UTC
