### ISSUE TITLE
EDv84 runtime error during patch fusion after 1st year

### ISSUE THREAD

**Issue by larsonej** [EDmodel/ED2#213] opened 2017-11-10 16:34 UTC
forrtl: severe (193): Run-Time Check Failure. The variable 'fuse_fiss_utils_mp_fuse_patches_$DARK_LAI80' is being used without being defined
Image              PC                Routine            Line        Source
ed_2.1-opt         00000000024500BD  fuse_fiss_utils_m        3771  fuse_fiss_utils.f90
ed_2.1-opt         0000000003315FB4  vegetation_dynami         124  vegetation_dynamics.f90
ed_2.1-opt         0000000000C2F11A  ed_model_                 379  ed_model.f90
ed_2.1-opt         0000000000413308  ed_driver_                269  ed_driver.f90
ed_2.1-opt         000000000040E545  MAIN__                    137  edmain.f90

This issues is not replicated in another version of the code.

**Comment by manfredo89** [comment] 2017-11-10 18:24
Did you set
ulimit -s unlimited
Sometimes the optimized binary gives segfault when ulimit is too small.

**Comment by larsonej** [comment] 2017-11-10 18:28
Yes.

**Comment by manfredo89** [comment] 2017-11-10 18:38
Are you using the main branch? Can you post the ED2IN so that we try to reproduce the run.

**Comment by manfredo89** [comment] 2017-11-10 18:45
Also which compiler version and options are you using?

**Comment by larsonej** [comment] 2017-11-10 19:02
This problem occurred with the main branch (v84) running on Odyssey. When I set MAXPATCH = 1, there was no error and the code ran fine for 3 years. 

I used the following compilers and libraries:
module load intel/15.0.0-fasrc01
module load openmpi/1.10.0-fasrc01
module load hdf5/1.8.12-fasrc07

Attached is the ED2IN file. 
[ED2IN.txt](https://github.com/EDmodel/ED2/files/1462421/ED2IN.txt)

**Comment by larsonej** [comment] 2017-11-10 19:03
Also, this was run on a single processor.

**Comment by mpaiao** [comment] 2017-11-10 19:17
@larsonej This looks like a genuine bug in the version you are using.  The error message is telling that DARK_LAI80 is never given an initial value before it's used.  MAXPATCH=1 forces the model to never create any new patch, this is why you don't see the problem. 

From your previous messages it looks like you are using a pretty old version of the code (you can check the commit date by typing git log).  Also, it seems you are compiling the code with debugging options, which may be good to sort out these issues, but not a good idea for actual scientific runs because the code will run much slower.

**Comment by manfredo89** [comment] 2017-11-10 19:23
Also if you are using Intel compilers do not use openmpi. Intel has its own mpi library. This is unrelated to your issue though. I think loading hdf5 should load everything you need (most likely the right compiler version comes with the module itself).

**Comment by larsonej** [comment] 2017-11-10 19:26
This version (v84) may be pretty old, but it's also the most recent version released on the main branch. I thought this bug should at least be noted on here.

**Comment by mpaiao** [comment] 2017-11-10 20:39
Perhaps you are referring to the old version control we used to use?
If this is the case, then I don't think there is anything special about v84, other than being the last revision we committed in bzr before we migrated to github.  Otherwise, could you please point me to this revision? Thanks.

**Comment by larsonej** [comment] 2017-11-10 20:58
I'm referring to the releases (https://github.com/EDmodel/ED2/releases), but I'm not sure if this is used anymore.

**Comment by mpaiao** [comment] 2017-11-10 21:02
This is just legacy from bzr, in that version control any update would be a release.

**Closed** 2018-01-17 20:26 UTC
